# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/GeertJohan/go.rice"

[[constraint]]
  name = "github.com/awalterschulze/gographviz"
  version = "2.0.0"

[[constraint]]
  name = "github.com/elazarl/go-bindata-assetfs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/k0kubun/pp"
  version = "2.3.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/config"

[[constraint]]
  revision = "eb0b9937d67b6bf363b1d177284d6c050e698821"
  name = "github.com/rai-project/dlframework"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/downloadmanager"

[[constraint]]
  name = "github.com/rai-project/go-mxnet-predictor"
  version = "0.3.16"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/image"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/logger"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/tracer"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "gopkg.in/fatih/set.v0"
  version = "0.1.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[override]]
  branch = "master"
  name = "github.com/apache/thrift"

[[override]]
  branch = "master"
  name = "github.com/VividCortex/robustly"

[prune]
  go-tests = true
  unused-packages = true
